Coco dataset loading
pascalbenschopTU/food_volume_estimation pull request #1
Opened 2023-05-24 10:45 UTC by janneskasper

2023-05-24 13:13 UTC, pascalbenschopTU requested changes

2023-05-24 13:13 UTC, pascalbenschopTU commented on food_recognition_options.py
> +VAL_IMAGE_DIRECTORY = "/home/jannes/Documents/MasterDelft/Q4/DeepLearning/datasets/food_rec/raw_data/public_validation_set_2.0/images/"
Could these be local and added to gitignore?

2023-05-24 13:17 UTC, janneskasper commented on food_recognition_options.py
> +VAL_IMAGE_DIRECTORY = "/home/jannes/Documents/MasterDelft/Q4/DeepLearning/datasets/food_rec/raw_data/public_validation_set_2.0/images/"
I dont see the point. They are only there to make running and debugging easier since you have to provide the parameters from the command line otherwise. Ill delete them in the end. You can put them into an extra file if you want to.

2023-05-28 19:17 UTC, pascalbenschopTU approved these changes

2023-05-28 19:17 UTC, merged